/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaxgradle;

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.fxml.FXMLLoader;


public class App extends Application{
	
    public static void main(String[] args) {
	 launch();
}
    @Override
    public void start(Stage primaryStage) throws Exception {
    	
    	FXMLLoader fxmlLoader = new FXMLLoader();
    	fxmlLoader.setLocation(getClass().getResource("/SceneBuilderAtividade"));
    	Parent conteudo = fxmlLoader.load();
    	
    	Scene cena = new Scene(conteudo,800, 600);
    	primaryStage.setTitle("Salve Rapaziada");
    	primaryStage.setScene(cena);
    	primaryStage.show();
    	  }
}